INSERT INTO "dimension"(name) values('Weight (kg)');
INSERT INTO "dimension"(name) values('Body Fat (%)');
INSERT INTO "dimension"(name) values('Waist (cm)');
INSERT INTO "dimension"(name) values('Neck (cm)');
INSERT INTO "dimension"(name) values('Shoulders (cm)');
INSERT INTO "dimension"(name) values('Chest (cm)');
INSERT INTO "dimension"(name) values('Left Bicep (cm)');
INSERT INTO "dimension"(name) values('Right Bicep (cm)');
INSERT INTO "dimension"(name) values('Left Forearm (cm)');
INSERT INTO "dimension"(name) values('Right Forearm (cm)');
INSERT INTO "dimension"(name) values('Hips (cm)');
INSERT INTO "dimension"(name) values('Left Thigh (cm)');
INSERT INTO "dimension"(name) values('Right Thigh (cm)');
INSERT INTO "dimension"(name) values('Left Calf (cm)');
INSERT INTO "dimension"(name) values('Right Calf (cm)');
