INSERT INTO "image"(link) values('ic_menu_chest');
INSERT INTO "image"(link) values('ic_menu_back');
INSERT INTO "image"(link) values('ic_menu_biceps');
INSERT INTO "image"(link) values('ic_menu_triceps');
INSERT INTO "image"(link) values('ic_menu_shoulders');
INSERT INTO "image"(link) values('ic_menu_trapeze');
INSERT INTO "image"(link) values('ic_menu_forearms');
INSERT INTO "image"(link) values('ic_menu_abs');
INSERT INTO "image"(link) values('ic_menu_quads');
INSERT INTO "image"(link) values('ic_menu_hamstrings');
INSERT INTO "image"(link) values('ic_menu_glutes');
INSERT INTO "image"(link) values('ic_menu_caviar');
INSERT INTO "image"(link) values('exercises/chest/image_barbell_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_barbell_incline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_barbell_decline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_decline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_smith_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_smith_machine_incline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_smith_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_flys.png');
INSERT INTO "image"(link) values('exercises/chest/image_push_ups.png');
INSERT INTO "image"(link) values('exercises/chest/image_chest_dips.png');
INSERT INTO "image"(link) values('exercises/chest/image_butterfly.png');
INSERT INTO "image"(link) values('exercises/chest/image_butterfly.png');
INSERT INTO "image"(link) values('exercises/chest/image_butterfly.png');
INSERT INTO "image"(link) values('exercises/chest/image_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_pullover.png');
INSERT INTO "image"(link) values('exercises/back/image_barbell_bent_over_row.png');
INSERT INTO "image"(link) values('exercises/back/image_barbell_reverse_grip_bent_over_row.png');
INSERT INTO "image"(link) values('exercises/back/image_barbell_deadlift.png');
INSERT INTO "image"(link) values('exercises/back/image_good_mornings.png');
INSERT INTO "image"(link) values('exercises/back/image_t_bar_row.png');
INSERT INTO "image"(link) values('exercises/back/image_dumbbell_deadlift.png');
INSERT INTO "image"(link) values('exercises/back/image_dumbbell_row.png');
INSERT INTO "image"(link) values('exercises/back/image_dumbbell_row.png');
INSERT INTO "image"(link) values('exercises/back/image_pull_ups.png');
INSERT INTO "image"(link) values('exercises/back/image_hyperextensions.png');
INSERT INTO "image"(link) values('exercises/back/image_gravitron_pull_up.png');
INSERT INTO "image"(link) values('exercises/back/image_lat_pulldown.png');
INSERT INTO "image"(link) values('exercises/back/image_lat_pulldown_behind_neck.png');
INSERT INTO "image"(link) values('exercises/back/image_seated_cable_row.png');
INSERT INTO "image"(link) values('exercises/back/image_v_bar_pulldown.png');
INSERT INTO "image"(link) values('exercises/back/image_t_bar_row.png');
INSERT INTO "image"(link) values('exercises/biceps/image_barbell_biceps_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_barbell_biceps_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_barbell_preacher_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_ez_bar_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_dumbbell_biceps_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_dumbbell_preacher_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_hammer_curls.png');
INSERT INTO "image"(link) values('exercises/biceps/image_hammer_curls.png');
INSERT INTO "image"(link) values('exercises/biceps/image_lying_incline_dumbbell_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_reverse_grip_pullups.png');
INSERT INTO "image"(link) values('exercises/biceps/image_cable_superman_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_standing_cable_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_standing_cable_curl.png');
INSERT INTO "image"(link) values('exercises/triceps/image_barbell_bench_press_reverse_grip.png');
INSERT INTO "image"(link) values('exercises/triceps/image_barbell_french_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_close_grip_bench_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_smith_machine_close_grip_bench_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_dumbbell_french_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_triceps_rope_pushdown.png');
INSERT INTO "image"(link) values('exercises/triceps/image_triceps_pushdown.png');
INSERT INTO "image"(link) values('exercises/triceps/image_reverse_grip_triceps_pushdown.png');
INSERT INTO "image"(link) values('exercises/triceps/image_triceps_dips.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_side_lateral_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_front_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_side_lateral_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_shoulder_press.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_barbell_front_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_barbell_shoulder_press.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_barbell_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_smith_machine_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_smith_machine_shoulder_press.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_cable_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_cable_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_cable_upright_row.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_barbell_shrug.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_cable_shrugs.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_dumbbell_shrug.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_smith_machine_shrug.png');
INSERT INTO "image"(link) values('exercises/forearms/image_barbell_wrist_curl.png');
INSERT INTO "image"(link) values('exercises/forearms/image_dumbbell_wrist_curl.png');
INSERT INTO "image"(link) values('exercises/forearms/image_cable_reverse_grip_curls.png');
INSERT INTO "image"(link) values('exercises/forearms/image_barbell_wrist_extension.png');
INSERT INTO "image"(link) values('exercises/forearms/image_dumbbell_wrist_extension.png');
INSERT INTO "image"(link) values('exercises/forearms/image_cable_reverse_grip_curls.png');
INSERT INTO "image"(link) values('exercises/abs/image_ab_crunch_machine.png');
INSERT INTO "image"(link) values('exercises/abs/image_knee_raise.png');
INSERT INTO "image"(link) values('exercises/abs/image_crunches.png');
INSERT INTO "image"(link) values('exercises/abs/image_rope_crunch.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_barbell_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_front_barbell_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_bulgarian_lunges.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_barbell_lunges.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_dumbbell_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_dumbbell_lunges.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_hack_squats.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_leg_extensions.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_leg_press.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_smith_machine_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_thigh_adductor.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_barbell_deadlift_hamstrings.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_romanian_deadlift.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_seated_leg_curl.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_lying_leg_curl.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_standing_leg_curl.png');
INSERT INTO "image"(link) values('exercises/glutes/image_glute_bridge.png');
INSERT INTO "image"(link) values('exercises/glutes/image_cable_kickback.png');
INSERT INTO "image"(link) values('exercises/glutes/image_glute_bridge.png');
INSERT INTO "image"(link) values('exercises/glutes/image_cable_sidekick.png');
INSERT INTO "image"(link) values('exercises/glutes/image_hyperextensions_glutes.png');
INSERT INTO "image"(link) values('exercises/glutes/image_romanian_deadlift_glutes.png');
INSERT INTO "image"(link) values('exercises/calves/image_seated_calf_raise.png');
INSERT INTO "image"(link) values('exercises/calves/image_calf_press_on_the_leg_press_machine.png');
INSERT INTO "image"(link) values('exercises/calves/image_smith_machine_calf_raises.png');
INSERT INTO "image"(link) values('exercises/calves/image_standing_calf_raises.png');
INSERT INTO "image"(link) values('exercises/chest/image_barbell_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_barbell_incline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_barbell_decline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_bench_press');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_decline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_smith_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_smith_machine_incline_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_smith_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_flys.png');
INSERT INTO "image"(link) values('exercises/chest/image_push_ups.png');
INSERT INTO "image"(link) values('exercises/chest/image_chest_dips.png');
INSERT INTO "image"(link) values('exercises/chest/image_butterfly.png');
INSERT INTO "image"(link) values('exercises/chest/image_butterfly.png');
INSERT INTO "image"(link) values('exercises/chest/image_butterfly.png');
INSERT INTO "image"(link) values('exercises/chest/image_machine_bench_press.png');
INSERT INTO "image"(link) values('exercises/chest/image_dumbbell_pullover.png');
INSERT INTO "image"(link) values('exercises/back/image_barbell_bent_over_row.png');
INSERT INTO "image"(link) values('exercises/back/image_barbell_reverse_grip_bent_over_row.png');
INSERT INTO "image"(link) values('exercises/back/image_barbell_deadlift.png');
INSERT INTO "image"(link) values('exercises/back/image_good_mornings.png');
INSERT INTO "image"(link) values('exercises/back/image_t_bar_row.png');
INSERT INTO "image"(link) values('exercises/back/image_dumbbell_deadlift.png');
INSERT INTO "image"(link) values('exercises/back/image_dumbbell_row.png');
INSERT INTO "image"(link) values('exercises/back/image_dumbbell_row.png');
INSERT INTO "image"(link) values('exercises/back/image_pull_ups.png');
INSERT INTO "image"(link) values('exercises/back/image_hyperextensions.png');
INSERT INTO "image"(link) values('exercises/back/image_gravitron_pull_up.png');
INSERT INTO "image"(link) values('exercises/back/image_lat_pulldown.png');
INSERT INTO "image"(link) values('exercises/back/image_lat_pulldown_behind_neck.png');
INSERT INTO "image"(link) values('exercises/back/image_seated_cable_row.png');
INSERT INTO "image"(link) values('exercises/back/image_v_bar_pulldown.png');
INSERT INTO "image"(link) values('exercises/back/image_t_bar_row.png');
INSERT INTO "image"(link) values('exercises/biceps/image_barbell_biceps_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_barbell_biceps_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_barbell_preacher_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_ez_bar_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_dumbbell_biceps_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_dumbbell_preacher_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_hammer_curls.png');
INSERT INTO "image"(link) values('exercises/biceps/image_hammer_curls.png');
INSERT INTO "image"(link) values('exercises/biceps/image_lying_incline_dumbbell_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_reverse_grip_pullups.png');
INSERT INTO "image"(link) values('exercises/biceps/image_cable_superman_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_standing_cable_curl.png');
INSERT INTO "image"(link) values('exercises/biceps/image_standing_cable_curl.png');
INSERT INTO "image"(link) values('exercises/triceps/image_barbell_bench_press_reverse_grip.png');
INSERT INTO "image"(link) values('exercises/triceps/image_barbell_french_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_close_grip_bench_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_smith_machine_close_grip_bench_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_dumbbell_french_press.png');
INSERT INTO "image"(link) values('exercises/triceps/image_triceps_rope_pushdown.png');
INSERT INTO "image"(link) values('exercises/triceps/image_triceps_pushdown.png');
INSERT INTO "image"(link) values('exercises/triceps/image_reverse_grip_triceps_pushdown.png');
INSERT INTO "image"(link) values('exercises/triceps/image_triceps_dips.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_side_lateral_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_front_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_side_lateral_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_dumbbell_shoulder_press.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_barbell_front_raise.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_barbell_shoulder_press.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_barbell_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_smith_machine_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_smith_machine_shoulder_press.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_cable_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_cable_upright_row.png');
INSERT INTO "image"(link) values('exercises/shoulders/image_cable_upright_row.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_barbell_shrug.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_cable_shrugs.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_dumbbell_shrug.png');
INSERT INTO "image"(link) values('exercises/trapezius/image_smith_machine_shrug.png');
INSERT INTO "image"(link) values('exercises/forearms/image_barbell_wrist_curl.png');
INSERT INTO "image"(link) values('exercises/forearms/image_dumbbell_wrist_curl.png');
INSERT INTO "image"(link) values('exercises/forearms/image_cable_reverse_grip_curls.png');
INSERT INTO "image"(link) values('exercises/forearms/image_barbell_wrist_extension.png');
INSERT INTO "image"(link) values('exercises/forearms/image_dumbbell_wrist_extension.png');
INSERT INTO "image"(link) values('exercises/forearms/image_cable_reverse_grip_curls.png');
INSERT INTO "image"(link) values('exercises/abs/image_ab_crunch_machine.png');
INSERT INTO "image"(link) values('exercises/abs/image_knee_raise.png');
INSERT INTO "image"(link) values('exercises/abs/image_crunches.png');
INSERT INTO "image"(link) values('exercises/abs/image_rope_crunch.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_barbell_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_front_barbell_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_bulgarian_lunges.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_barbell_lunges.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_dumbbell_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_dumbbell_lunges.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_hack_squats.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_leg_extensions.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_leg_press.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_smith_machine_squat.png');
INSERT INTO "image"(link) values('exercises/quadriceps/image_thigh_adductor.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_barbell_deadlift_hamstrings.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_romanian_deadlift.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_seated_leg_curl.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_lying_leg_curl.png');
INSERT INTO "image"(link) values('exercises/hamstrings/image_standing_leg_curl.png');
INSERT INTO "image"(link) values('exercises/glutes/image_glute_bridge.png');
INSERT INTO "image"(link) values('exercises/glutes/image_cable_kickback.png');
INSERT INTO "image"(link) values('exercises/glutes/image_glute_bridge.png');
INSERT INTO "image"(link) values('exercises/glutes/image_cable_sidekick.png');
INSERT INTO "image"(link) values('exercises/glutes/image_hyperextensions_glutes.png');
INSERT INTO "image"(link) values('exercises/glutes/image_romanian_deadlift_glutes.png');
INSERT INTO "image"(link) values('exercises/calves/image_seated_calf_raise.png');
INSERT INTO "image"(link) values('exercises/calves/image_calf_press_on_the_leg_press_machine.png');
INSERT INTO "image"(link) values('exercises/calves/image_smith_machine_calf_raises.png');
INSERT INTO "image"(link) values('exercises/calves/image_standing_calf_raises.png');


INSERT INTO "category"(name, image_id) values('Chest', 1);
INSERT INTO "category"(name, image_id) values('Back', 2);
INSERT INTO "category"(name, image_id) values('Biceps', 3);
INSERT INTO "category"(name, image_id) values('Triceps', 4);
INSERT INTO "category"(name, image_id) values('Shoulders', 5);
INSERT INTO "category"(name, image_id) values('Trapezius', 6);
INSERT INTO "category"(name, image_id) values('Forearms', 7);
INSERT INTO "category"(name, image_id) values('Abs', 8);
INSERT INTO "category"(name, image_id) values('Quads', 9);
INSERT INTO "category"(name, image_id) values('Hamstrings', 10);
INSERT INTO "category"(name, image_id) values('Glutes', 11);
INSERT INTO "category"(name, image_id) values('Calves', 12);

INSERT INTO "dimension"(name) values('Руки');
INSERT INTO "dimension"(name) values('Предплечья');
INSERT INTO "dimension"(name) values('Шея');
INSERT INTO "dimension"(name) values('Грудь');
INSERT INTO "dimension"(name) values('Талия');
INSERT INTO "dimension"(name) values('Бедра');
INSERT INTO "dimension"(name) values('Икры');

INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  13,  123, 'Bench Press', 'Barbell', 'The bench press is a basic exercise with free weights. The exercise is performed with a barbell on a bench.',  '1. Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.\n 2. Lower the bar to your mid chest\n 3. Raise the bar until you locked your elbows');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  14,  124, 'Incline Bench Press', 'Barbell', 'The incline bench press is a variation of the bench press. Using an incline will allow you to better target your upper chest, a lagging area for many lifters. The exercise is performed with a barbell on a bench with an incline of 30°.', '1. Position the bench between 30 and 45 degrees.\n2. Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.\n3. Lower the bar to your mid chest \n4. Raise the bar (slowly and controlled) until you locked your elbows.');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  15,  125, 'Decline Bench Press', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  16,  126, 'Bench Press', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  17,  127, 'Incline Bench Press', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  18,  128, 'Decline Bench Press', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  19,  129, 'Bench Press', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  20,  130, 'Incline Bench Press', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  21,  131, 'Decline Bench Press', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  22,  132, 'Bench Press', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  23,  133, 'Incline Bench Press', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  24,  134, 'Incline Chest Flys', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  25,  135, 'Push Up', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  26,  136, 'Chest Dips', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  27,  137, 'Chest Fly', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  28,  138, 'Incline Chest Fly', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  29,  139, 'Decline Chest Fly', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  30,  140, 'Chest Press', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(1,  31,  141, 'Pullover', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  32,  142, 'Bent Over Row', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  33,  143, 'Reverse Grip Bent Over Row', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  34,  144, 'Deadlift', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  35,  145, 'Good Mornings', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  36,  146, 'T-Bar Rows', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  37,  147, 'Deadlift', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  38,  148, 'Row Bilateral', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  39,  149, 'Row Unilateral ', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  40,  150, 'Pull Ups', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  42,  151, 'Hyperextension', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  43,  152, 'Pull Ups', 'Gravitron', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  44,  153, 'Lat Pulldown ', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  45,  154, 'Behind Neck Lat Pulldown ', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  46,  155, 'Seated Cable Row', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  47,  156, 'V-Bar Pulldown ', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(2,  48,  157, 'T-Bar Row ', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  49,  158, 'Curls', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  50,  159, 'Reverse Curls', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  51,  160, 'Preacher Curls', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  52,  161, 'Curls', 'EZ-Bar', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  53,  162, 'Curls', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  54,  163, 'Preacher Curls', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  55,  164, 'Hammer Curls', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  56,  165, 'Reverse Curls', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  57,  166, 'Incline Lying Curls', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  58,  167, 'Chin Ups', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  59,  168, 'Superman Curls', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  60,  169, 'Standing Curls', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(3,  61,  170, 'Hammer Curls', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  62,  171, 'French Press', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  63,  172, 'Close Grip Bench Press', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  64,  173, 'Close Grip Bench Press', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  65,  174, 'Skullcrusher', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  66,  175, 'Overhead Extension', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  67,  176, 'Rope Pushdown', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  68,  177, 'Pushdown', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  69,  178, 'Reverse Grip Pushdown', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(4,  70,  179, 'Dips', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  71,  180, 'Lateral Raise', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  72,  181, 'Front Raise', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  73,  182, 'Rear Delt Fly', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  74,  183, 'Overhead Press', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  75,  184, 'Front Raise', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  76,  185, 'Overhead Press', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  77,  186, 'Upright Row', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  78,  187, 'Upright Row', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  79,  188, 'Overhead Press', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  80,  189, 'Rope Face Pulls', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  81,  190, 'Lateral Raise', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(5,  82,  191, 'Upright Row', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(6,  83,  192, 'Shrugs', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(6,  84,  193, 'Shrugs', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(6,  85,  194, 'Shrugs', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(6,  86,  195, 'Shrugs', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(7,  87,  196, 'Wrist Curl', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(7,  88,  197, 'Wrist Curl', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(7,  89,  198, 'Wrist Curl', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(7,  90,  199, 'Wrist Extension', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(7,  91,  200, 'Wrist Extension', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(7,  92,  201, 'Wrist Extension', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(8,  93,  202, 'Crunches', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(8,  94,  203, 'Knee Raises', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(8,  95,  204, 'Crunches', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(8,  96,  205, 'Rope Crunches', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  97,  206, 'Squat', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  98,  207, 'Front Squat', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  99,  208, 'Bulgarian Squat', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  100, 209, 'Lunges', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  101, 210, 'Squat', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  102, 211, 'Lunges', 'Dumbbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  103, 212, 'Hack Squat', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  104, 213, 'Leg Extensions', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  105, 214, 'Leg Press', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  106, 215, 'Squat', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(9,  107, 216, 'Thigh Adductor', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(10, 108, 217, 'Deadlift', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(10, 109, 218, 'Romanian Deadlift', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(10, 110, 219, 'Seated Leg Curls', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(10, 111, 220, 'Lying Leg Curls', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(10, 112, 221, 'Standing Leg Curls', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(11, 113, 222, 'Hip Thrust', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(11, 114, 223, 'Kickback', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(11, 115, 224, 'Glute Bridge', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(11, 116, 225, 'Side Kick', 'Cable', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(11, 117, 226, 'Hyperextension', 'Body weight', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(11, 118, 227, 'Romanian Deadlift', 'Barbell', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(12, 119, 228, 'Seated Calf Raises', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(12, 120, 229, 'Calf Press', 'Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(12, 121, 230, 'Calf Raises', 'Smith Machine', '', '');
INSERT INTO "exercise"(category_id, icon_id, image_id, name, equipment, description, technique) values(12, 122, 231, 'Standing Calf Raises', 'Body weight', '', '');